name = input("What is your name?: ")
favoriteFood = input("What's your favorite meal?: ")
favoriteMusic = input("What's your favorite song?: ")
location = input("Where do you live?: ")

print()
print("So your name is")
print(name)
print("and your favorite meal is")
print(favoriteFood)
print("You live in")
print(location)
print("and you love rocking out to")
print(favoriteMusic)
print("during your leisure time. Pretty cool man, rock on 🤘🤘")